[DC-2212] Remove SNOMED code descendants of 141771 and 4054924
all-of-us/curation pull request #1157
Opened 2022-03-07 16:34 UTC by ksdkalluri

2022-03-08 22:04 UTC, lrwb-aou requested changes
Please add the new class to the `REGISTERED_TIER_DEID_CLEANING_CLASSES` and `CONTROLLED_TIER_DEID_CLEANING_CLASSES` in clean_cdr.py.

2022-03-08 22:26 UTC, lrwb-aou requested changes
Good turn around on this one.  Just a few suggestions.  Thanks!

2022-03-08 22:26 UTC, lrwb-aou commented on data_steward/cdr_cleaner/cleaning_rules/vehicular_accident_concept_suppression.py
> +  `{{project_id}}.{{dataset_id}}..concept` c
```suggestion
  `{{project_id}}.{{dataset_id}}.concept` c
```

2022-03-08 22:26 UTC, lrwb-aou commented on data_steward/cdr_cleaner/cleaning_rules/vehicular_accident_concept_suppression.py
> +            affected_datasets=[cdr_consts.REGISTERED_TIER_DEID],
also affects controlled tier.

2022-03-08 22:26 UTC, lrwb-aou commented on data_steward/cdr_cleaner/cleaning_rules/vehicular_accident_concept_suppression.py
> +CREATE OR REPLACE TABLE `{{project_id}}.{{sandbox_id}}.{{concept_suppression_lookup_table}}` AS
I think this works as is, but the Create table docs seem to suggest enclosing the query in ().

2022-03-08 22:26 UTC, lrwb-aou commented on tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/vehicular_accident_concept_suppression_test.py
> +                       (101, 2, 4054924, date('2020-01-01'), timestamp('2020-01-01'), 0, 0),
please add a record using the concept_id 44822621 in a `*_concept_id` field.  This should be dropped.

2022-03-09 15:32 UTC, lrwb-aou approved these changes
Thank you for the changes!  This looks good.

2022-03-09 17:44 UTC, ksdkalluri commented on data_steward/cdr_cleaner/clean_cdr.py
>      (MotorVehicleAccidentSuppression,),
we can do that, sure, we can do it post pipeline execution.

2022-03-09 17:45 UTC, merged