Bg/dc 2282
all-of-us/curation pull request #1184
Opened 2022-03-22 20:52 UTC by brendagutman

2022-03-23 16:20 UTC, mark-velez commented
@hiro-mishima I know you're currently looking at the associated data please chime in if you get a minute

2022-03-24 19:21 UTC, hiro-mishima requested changes
Thanks for this PR, @brendagutman ! I left some comments.

2022-03-24 19:21 UTC, hiro-mishima commented on data_steward/cdr_cleaner/manual_cleaning_rules/update_questiona_answers_not_mapped_to_omop.py
> +            pmi_code AS short_pmi_code,
Now that we no longer truncate `pmi_code` to 50 char, I think we no longer need to rename it as `short_pmi_code`.

2022-03-25 16:53 UTC, hiro-mishima approved these changes
Thanks for updating the script, Brenda! I think now it is good to go :sparkles:

2022-03-25 17:09 UTC, merged