[DC-2352] Add --run_as and --pmi_email params to deid_runner.sh
all-of-us/curation pull request #1213
Opened 2022-04-15 20:06 UTC by hiro-mishima

2022-04-18 19:14 UTC, jp3477 requested changes
@hiro-mishima Left some comments below. Let me know if my understanding is correct.

2022-04-18 19:14 UTC, jp3477 commented on data_steward/tools/deid_runner.sh
> +python "${CLEANER_DIR}/clean_cdr.py" --project_id "${APP_ID}" --dataset_id "${registered_cdr_deid}" --run_as "${run_as}" --sandbox_dataset_id "${registered_cdr_deid_sandbox}" --data_stage ${data_stag
The `deid_questionnaire_response_map_dataset` argument is hardcoded here. Should it be a variable from a shell script command line argument?

2022-04-18 19:14 UTC, jp3477 commented on data_steward/tools/deid_runner.sh
> +  --pmi_email <pmi-ops account email>
Should `deid_questionnaire_response_map_dataset` be added here as an argument?

2022-04-18 20:09 UTC, hiro-mishima commented
Thanks, @jp3477 for reviewing! I updated the script. It would be great if you could have a look at it again. Thanks!

2022-04-19 16:31 UTC, ksdkalluri approved these changes
We tested the changes in the last run, Good to merge.

2022-04-19 18:07 UTC, merged