[DC-2184] Update RT cleaning classes lists to make it work with create_tier
all-of-us/curation pull request #1251
Opened 2022-05-09 22:05 UTC by ksdkalluri

2022-05-11 20:43 UTC, hiro-mishima requested changes
I left a few comments. Could you please check if those make sense? Thanks, @ksdkalluri!

2022-05-11 20:43 UTC, hiro-mishima commented on data_steward/cdr_cleaner/manual_cleaning_rules/survey_version_info.py
> +            affected_datasets=[cdr_consts.REGISTERED_TIER_DEID],
I think we also need to add `CONTROLLED_TIER_DEID` to this list.

2022-05-11 20:43 UTC, hiro-mishima commented on data_steward/cdr_cleaner/cleaning_rules/clean_mapping.py
> +                             cdr_consts.RDR, cdr_consts.COMBINED,
I don't think we need `RDR` here. We need `EHR` and `UNIONED` instead.

2022-05-11 20:43 UTC, hiro-mishima commented
And it looks like there is a conflict.

2022-05-11 21:40 UTC, ksdkalluri commented
> And it looks like there is a conflict.

Resolved them as well

2022-05-12 12:57 UTC, hiro-mishima approved these changes
Looks good! Thanks, @ksdkalluri 🎉

2022-05-12 13:08 UTC, merged