[DC-1930] Fully convert deactivation data script to cleaning rule
all-of-us/curation pull request #1289
Opened 2022-06-14 21:48 UTC by nishanthpp93

* [DC-1930] Update deactivation CR

2022-06-24 19:04 UTC, hiro-mishima requested changes
Thanks for refactoring the scripts, @nishanthpp93! I added a few minor suggestions for changes. Please let me know if you have any questions. Thank you🙂

2022-07-01 18:17 UTC, nishanthpp93 commented on data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date.py
> +DEACTIVATION_ISSUE_NUMBERS = ['DC686', 'DC1184', 'DC1799']
Yeah, I think they are helpful to keep but don't want the names to get too long.

2022-07-01 18:17 UTC, nishanthpp93 commented on data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date.py
> +SELECT *
Good point, will update this.

2022-07-01 19:06 UTC, nishanthpp93 commented on data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date.py
> +SELECT *
This seems harder to implement due to fitbit tables not having an id column. Currently this is schema agnostic. Let me know your thoughts.

2022-07-06 13:28 UTC, hiro-mishima commented on data_steward/cdr_cleaner/cleaning_rules/remove_participant_data_past_deactivation_date.py
> +SELECT *
You are right. I think this is out of this ticket's scope. Let's leave it as it is.

2022-07-06 13:29 UTC, hiro-mishima approved these changes
Thanks, @nishanthpp93! It all looks good!

2022-07-06 15:21 UTC, merged