[DC-2630] Update remove_participant_under_18years cleaning rule to include the survey_conduct table
all-of-us/curation pull request #1378
Opened 2022-08-31 18:35 UTC by nishanthpp93

* [DC-2630] Update remove_participants_under_18years with CATI tables

2022-08-31 19:42 UTC, ksdkalluri requested changes
@nishanthpp93 I would say add the ticket number to the issue numbers.

2022-09-07 14:52 UTC, molly-giddings approved these changes

2022-09-07 14:56 UTC, molly-giddings commented
Hi @ksdkalluri - I approved this review but I think you need to approve your requested change as well.

2022-09-07 15:25 UTC, ksdkalluri approved these changes

2022-09-07 15:30 UTC, merged