[DC-2733] Bug Fixes in `create_combined_dataset` stage
all-of-us/curation pull request #1420
Opened 2022-09-29 21:42 UTC by ksdkalluri

2022-10-19 21:00 UTC, hiro-mishima requested changes
Thank you so much for your great work, @ksdkalluri! I have some questions and suggestions. I do not think any of them is major. Please let me know if you have any questions. Thanks again :)

2022-10-24 19:36 UTC, ksdkalluri commented on data_steward/tools/create_combined_backup_dataset.py
> +                          bq_client=client)
I updated, the add_cdr_metadata to take in bq_client as a parameter. so we do not create a new client again in the script. doing like this we can write the logs to the same cloud trace.

2022-10-25 19:35 UTC, hiro-mishima commented on data_steward/tools/create_combined_backup_dataset.py
> +                          bq_client=client)
Oh, that makes sense! Thanks for the explanation.

2022-10-25 19:48 UTC, hiro-mishima commented on data_steward/tools/create_combined_backup_dataset.py
> +            col_expr = f'{field_name[:3] + "_" + field_name[-7:-3] if "_" in field_name else field_name[:3]}.' \
Thanks for the explanation! That makes sense. And now I understand the reason why it is `-3`. It is to avoid `_id` being part of the alias.

2022-10-25 19:50 UTC, hiro-mishima approved these changes
Thanks a lot, @ksdkalluri! It looks great🎉

2022-10-26 16:12 UTC, merged