[DC-3047] Fix the 'NOT RUN' bug in check_controlled_tier.py
all-of-us/curation pull request #1530
Opened 2023-03-09 19:36 UTC by brendagutman

2023-03-13 14:52 UTC, brendagutman commented on data_steward/analytics/cdr_ops/controlled_tier_qc/code/controlled_tier_qc.py
> +
Moved from below so changes to 'note' would be together. I did the same in the else statement.

2023-03-13 17:05 UTC, ksdkalluri requested changes
@brendagutman, changes look good to make this work. Can you also update the analytics/cdr_ops/controlled_tier_qc/Readme.md and add in point that check needs to be added in two places. Thanks!

2023-03-13 17:21 UTC, brendagutman commented
> @ksdkalluri  I added an acceptance criteria to the resulting ticket [DC-3125](https://precisionmedicineinitiative.atlassian.net/browse/DC-3125). To add the check to the README and to `to_include`.

2023-03-24 16:39 UTC, ksdkalluri reviewed
hey @brendagutman we still need to update the README for this ticket.

2023-03-24 17:04 UTC, ksdkalluri approved these changes

2023-03-24 19:08 UTC, merged