[DC-3210] Add check for HPro Deceased
all-of-us/curation pull request #1609
Opened 2023-05-24 21:52 UTC by hiro-mishima

2023-05-31 16:43 UTC, brendagutman requested changes
I had a few questions. Otherwise looks really good. Thanks for consolidating the queries, that should help with the organization of this notebook.

2023-06-01 16:25 UTC, hiro-mishima commented on data_steward/analytics/cdr_ops/raw_rdr_export_qc.py
> +-- OR src_id != 'healthpro' --
Thanks for pointing it out! It was meant to be uncommented. For the pass/fail statement, the `render_message()` on line 855 will take care of it.

And clean_rdr_export_qc.py does not need the condition. The death table will not have a `src_id` column after the clean RDR process. 
The definition of `death` when we receive it from RDR -> [here](https://github.com/all-of-us/curation/blob/develop/data_steward/resource_files/schemas/rdr_src_id/tables/rdr_death.json)
The definition of `death` at the time we run clean_rdr_export_qc.py -> [here](https://github.com/all-of-us/curation/blob/develop/data_steward/resource_files/schemas/cdm/clinical/death.json)

2023-06-01 20:35 UTC, brendagutman commented on data_steward/analytics/cdr_ops/raw_rdr_export_qc.py
> +-- OR src_id != 'healthpro' --
Thank you for the very thorough explanation!

2023-06-01 20:36 UTC, brendagutman approved these changes
Looks good Hiro!

2023-06-02 12:45 UTC, merged