[DC-3260] Update PERSON_EXT_TABLE_QUERY in create_person_ext_table.py to populate state_of_residence and sex_at_birth columns without recreating person_ext table.
all-of-us/curation pull request #1642
Opened 2023-07-03 19:23 UTC by ksdkalluri

2023-07-06 20:07 UTC, lledezma commented on data_steward/cdr_cleaner/cleaning_rules/create_person_ext_table.py
>  state_of_residence_concept_id: the value_source_concept_id field in the OBSERVATION table row where
This same comment is present in the integration and unit test. I would also remove it from there.

2023-07-06 20:11 UTC, lledezma requested changes
Updates look good! I would also add the ticket number to the `issue_numbers` list and as one the the original issues in the docstrings.

2023-07-11 14:09 UTC, ksdkalluri commented
> Updates look good! I would also add the ticket number to the `issue_numbers` list and as one of the original issues in the docstrings.

Updated the docstring and added the `issue_number`

2023-07-12 20:43 UTC, lledezma requested changes
Thanks for the updates! I would also update the docstring in the unit test.

2023-08-17 18:37 UTC, lledezma approved these changes

2023-08-17 18:42 UTC, merged