[DC-3607] Create cleaning rule to remove notes from CDR
all-of-us/curation pull request #1817
Opened 2023-11-30 20:56 UTC by MichaelSchmidt82

Notes submitted by sites and RDR must be suppressed since they are not being released soon.
This cleaning rule replaces note_text with `NO_TEXT` and note_title with `NO_TITLE` in the combined stage.

This test checks all four cases:

1. An unacceptable value in note_title
2. An inappropriate value in note_text
3. Both note_title and note_text contain wrong values.
4. Both note_title and note_text contain acceptable values.
5. Both note_title and note_text are empty strings `""`

Original Issues: DC-3607

2023-12-01 16:31 UTC, ksdkalluri requested changes
Looks good @MichaelSchmidt82 I suggested a slight modification to your query and suggested 2 more test scenarios for the integration test.

2023-12-01 18:04 UTC, MichaelSchmidt82 commented on tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/replace_freetext_notes_test.py
> +              (4, 40, DATE('2023-01-01'), TIMESTAMP('2023-01-01 00:00:00'), 0, 0, 'NO_TITLE', 'NO_TEXT', 0, 0)
Gotcha

2023-12-01 18:29 UTC, MichaelSchmidt82 commented on data_steward/cdr_cleaner/cleaning_rules/replace_freetext_notes.py
> +    note_title = CASE WHEN NOT REGEXP_CONTAINS('note_title', '(?i)NO_TITLE') THEN 'NO_TITLE'
thanks for that.  I felt it was costly

2023-12-01 20:10 UTC, MichaelSchmidt82 commented on tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/replace_freetext_notes_test.py
> +              (4, 40, DATE('2023-01-01'), TIMESTAMP('2023-01-01 00:00:00'), 0, 0, 'NO_TITLE', 'NO_TEXT', 0, 0)
archiving `NULL` is an error as those fields are required.

2023-12-05 14:56 UTC, ksdkalluri approved these changes
Good to merge @MichaelSchmidt82 !

2023-12-05 15:52 UTC, merged