[DC-3631] Update cope_survey to reduce false positive results due to concept domains
all-of-us/curation pull request #1827
Opened 2023-12-14 20:19 UTC by MichaelSchmidt82

**Background:**
"The issue with the `procedure_occurence` covid vaccine concepts failing due to 'being suppressed in RT' is caused by the vocabulary `domain_id`'s for the associated Standard concepts which populate `procedure_concept_id` (failing column) being 'Drug' in the combined stage. These records are not actually suppressed they get moved to the Drug table by a combined CR."

**This PR:**
Updated to look for concepts that are being suppressed in the deid stage. 
- If they existed at combined stage, they should still be in deid.
- If they did not exist in combined stage, they should not be expected to exist in died.

See Jira issue [DC-3631](https://precisionmedicineinitiative.atlassian.net/browse/DC-3631) for the complete description and scope
See Jira issue [DC-3625](https://precisionmedicineinitiative.atlassian.net/browse/DC-3625) for the investigation.

2023-12-19 17:19 UTC, ksdkalluri requested changes
@MichaelSchmidt82 I requested for few changes, once you make the changes please test the updates and push them.

2023-12-19 17:19 UTC, ksdkalluri commented on data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
> +FROM `{{project_id}}.{{deid_cdr}}.procedure_occurrence` c
Here it should not be `procedure_occurrence` it should be `{{table_name}}`. The table_name in the ticket is added for using it as example and testing. if you are looping through tables and columns for in your case this should be templated to as all other ones.

2023-12-19 17:19 UTC, ksdkalluri commented on data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
> +        FROM `{{project_id}}.{{com_cdr}}.procedure_occurrence` c
Same here with the `procedure_occurrence`, it should be `{{table_name}}`.

2023-12-19 17:19 UTC, ksdkalluri commented on data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
> +pipeline = "" # the pipeline tables
Why was this added to the notebook if it is used no where in the code?

2023-12-20 19:01 UTC, ksdkalluri requested changes

2023-12-20 21:14 UTC, MichaelSchmidt82 commented on data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report7_cope_survey.py
> +sandbox = "" # sandbox dataset
Based on your comment earlier, I put this back.  The description should be better, so I'll clarify.

2023-12-21 15:34 UTC, ksdkalluri approved these changes

2023-12-21 19:37 UTC, merged