[DC-3635] Remove portion of query checking primary consent
all-of-us/curation pull request #1834
Opened 2023-12-18 15:27 UTC by MichaelSchmidt82

WIP

2023-12-19 17:35 UTC, ksdkalluri requested changes
@MichaelSchmidt82 there is also a similar check in `check_controlled_tier_part2.py` that checks for primary consent for wear participants that needs to be removed as well as per the scope of the ticket.

2023-12-20 15:17 UTC, MichaelSchmidt82 commented
> @MichaelSchmidt82 there is also a similar check in `check_controlled_tier_part2.py` that checks for primary consent for wear participants that needs to be removed as well as per the scope of the ticket.

Good catch!

2023-12-21 15:33 UTC, ksdkalluri approved these changes

2023-12-21 15:33 UTC, ksdkalluri commented on data_steward/analytics/cdr_ops/rt_cdr_qc/cdr_deid_qa_report10_extra.py
> -
@MichaelSchmidt82 you would also need to update the comment for this check to remove primary_consent related  info.

2023-12-21 19:37 UTC, merged