[DC-1058] Modify Numeric PPI response cleaning rule to include "6+" generalization
all-of-us/curation pull request #611
Opened 2020-09-11 18:04 UTC by dcampbell-vumc

* Modified query to include new AOU concept code
* Modified integration test to properly test changes to cleaning rule

2020-09-11 20:19 UTC, lrwb-aou requested changes
I left question for Caroline and Heather on the ticket.  The test works as designed, but fails on edge cases.  I'm attaching a patch file that updates this test and the 11+ test with edge case testing.  Apply it, view the message, and create your fix.
[clean_ppi_edge_case_tests.txt](https://github.com/all-of-us/curation/files/5211358/clean_ppi_edge_case_tests.txt)

2020-09-14 15:02 UTC, lrwb-aou requested changes
Your business logic in `data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py` is broken based on the criteria in your ticket.  The test patch was provided to hightlight the broken business logic.

2020-09-14 19:47 UTC, dcampbell-vumc commented on tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py
> +        self.dc_1058_value_as_concept_id = 2000000012
You're right, I wouldn't even remember what is happening after a week :p, I changed them to have more descriptive variable names

2020-09-14 21:34 UTC, lrwb-aou commented on tests/integration_tests/data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters_test.py
> +                               (543, 0, self.value_as_number, 543, 1585890)],
```suggestion
                               (543, 0, self.value_as_number, self.six_plus_value_as_concept_id, 1585890)],
```

2020-09-14 21:36 UTC, lrwb-aou requested changes
The code in the cleaning rule is wrong.  I added the correct test condition.  I expect it to fail until the rule is corrected.

2020-09-16 20:12 UTC, lrwb-aou requested changes
This is my fault.  I didn't have the comment on the ticket completely correct.  I have updated that comment and am providing a patch file to make the changes here.  Please, try it and see if it makes sense with what we know we are supposed to be seeing.
[clean_ppi_patch.txt](https://github.com/all-of-us/curation/files/5234709/clean_ppi_patch.txt)

2020-09-17 16:36 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/cleaning_rules/clean_ppi_numeric_fields_using_parameters.py
> +    WHEN observation_source_concept_id IN (1333023, 1585890) AND (value_as_number < 0 OR value_as_number > 5) THEN NULL
Yes, this makes sense to me.

2020-09-17 19:22 UTC, lrwb-aou approved these changes
This looks right.  Now every test that expects a Null value for value_as_number has a generalized value for value_as_concept_id.  Thank you for working through this!

2020-09-17 19:40 UTC, merged