[DC-1019] Create test buckets and datasets in Python replacing bash scripts
all-of-us/curation pull request #672
Opened 2020-11-16 22:02 UTC by lrwb-aou

* uses python to create test buckets and datasets.

2020-11-17 19:11 UTC, dcampbell-vumc requested changes
Just a question about the unused `import os` statements in `create_datasets.py` and `create_buckets.py` and whether we can get rid of it or not.

2020-11-17 20:44 UTC, lrwb-aou commented on data_steward/ci/create_buckets.py
> +import os
nice catch!

2020-11-17 20:45 UTC, lrwb-aou commented on data_steward/ci/create_datasets.py
> +import os
good catch.

2020-11-18 14:31 UTC, dcampbell-vumc approved these changes
Changing the names of the modules to `test_*` and adding a module description clears up any confusion about what the modules are doing!

2020-11-19 15:27 UTC, merged