[DC-813] Update Temporal Data Point CR to New Base Class & Correct Pi…
all-of-us/curation pull request #709
Opened 2021-01-22 20:20 UTC by amcgrenera-vumc

…peline Step

2021-01-25 21:03 UTC, dcampbell-vumc requested changes
Do you think we should add a sandboxing query? I commented a sandbox query suggestion but it hasn't been tested. I am not sure if it would be too difficult to add something like that or not.

2021-01-25 21:03 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py
> +            'Returns queries to updated end dates, end dates should not be prior to any start date'
nit:
```suggestion
            'Returns queries to update end dates, end dates should not be prior to any start date'
```

2021-01-26 14:59 UTC, amcgrenera-vumc commented on data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py
> +
Good question! Let me ask in the eng channel, I would think we should and this seems like an older cleaning rule before that was put in place, but I'll double check!

2021-01-26 16:37 UTC, amcgrenera-vumc commented on data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py
> +
Krishna said yes, so I will be adding!

2021-01-26 20:13 UTC, amcgrenera-vumc commented
@dcampbell-vumc now updated with sandboxing!

2021-01-26 22:18 UTC, dcampbell-vumc approved these changes
This looks good to me! Thanks for adding the sandboxing class!

2021-01-26 22:18 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/cleaning_rules/temporal_consistency.py
> +SANDBOX_BAD_END_DATES = JINJA_ENV.from_string("""
looks great!

2021-01-26 22:56 UTC, merged