added hpo site id to observation id
all-of-us/curation pull request #817
Opened 2021-04-05 19:30 UTC by jp3477

Adds an integer representing the HPO site to the observation id in order to eliminate duplicates.

2021-04-06 16:33 UTC, ksdkalluri requested changes
Hi, @jp3477  this approach looks good. is it possible to add a unit test to test the constant factor generation?

2021-04-06 16:43 UTC, jp3477 commented
> Hi, @jp3477 this approach looks good. is it possible to add a unit test to test the constant factor generation?

Sure, will add one.

2021-04-08 13:40 UTC, ksdkalluri approved these changes
.Looks good to me! but the integration tests are failing for ehr_union_test and this is good to merge upon fixing them.

2021-04-12 13:28 UTC, ksdkalluri approved these changes

2021-04-12 13:30 UTC, merged