[DC-1543] convert storage script to cleaning rule
all-of-us/curation pull request #818
Opened 2021-04-05 19:48 UTC by lrwb-aou

* converts the previous storage script to a multi-stage cleaning rule
* stores the pids and generated shifts in a sandbox before appending to primary pid/rid table.  this will allow more identification if something unexpected happens.

2021-04-06 15:45 UTC, dcampbell-vumc requested changes
This all looks good, just a couple of nit picks. 

There isn't an integration test created for this yet so for me to test this, I printed out all the queries, popped them in BQ to at least see what data ended up populated in the created `stage_less_dc1543_pid_rid_mapping` sandbox table. It all looked right to me in the end!

2021-04-06 15:45 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/cleaning_rules/store_pid_rid_mappings.py
> +""")
Thanks for these comments!

2021-04-06 19:46 UTC, lrwb-aou commented
> This all looks good, just a couple of nit picks.
> 
> There isn't an integration test created for this yet so for me to test this, I printed out all the queries, popped them in BQ to at least see what data ended up populated in the created `stage_less_dc1543_pid_rid_mapping` sandbox table. It all looked right to me in the end!

You're right.  The integration test will be a separate issue.  I've already started working on it.  👍

2021-04-06 19:49 UTC, lrwb-aou commented on data_steward/cdr_cleaner/clean_cdr.py
> +    (StoreNewPidRidMappings,),
The order is not important for this rule.  It is reading a standalone table, writing to a sandbox table for good measure, then updating a primary table.  Do you have a suggestion for a better location?

2021-04-06 19:49 UTC, lrwb-aou commented on data_steward/cdr_cleaner/cleaning_rules/store_pid_rid_mappings.py
> +import time
Nice catch.  They should be removed.

2021-04-06 20:03 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/clean_cdr.py
> +    (StoreNewPidRidMappings,),
Nope, this is fine. I remember for the CT cleaning rules, we had specific location comments for some cleaning rules.

2021-04-06 21:13 UTC, lrwb-aou commented on data_steward/cdr_cleaner/cleaning_rules/store_pid_rid_mappings.py
> +import time
```suggestion
import logging
```

2021-04-06 21:16 UTC, lrwb-aou commented
@dcampbell-vumc I made some changes.  Let me know how they look.

2021-04-07 13:35 UTC, dcampbell-vumc approved these changes
This is good to go!

2021-04-08 17:49 UTC, merged