[DC-706] Modify parameters of cleaning rule from DC-584
all-of-us/curation pull request #875
Opened 2021-05-14 22:01 UTC by nishanthpp93

* [DC-706] Separate out queries for missing basics and missing ehr data
* [DC-706] Consider all pid tables for deletion
* [DC-706] Sandbox person rows before deleting
* [DC-706] Use dict and add back basics constant

2021-05-19 14:04 UTC, jp3477 requested changes
I added a note about converting the cleaning rules to the base class implementation.
Additionally, one of the integration tests, `drop_participants_without_ppi_or_ehr_test.py` is failing and needs to be updated. Other than that, everything looks good.

2021-05-19 19:32 UTC, nishanthpp93 commented on data_steward/cdr_cleaner/cleaning_rules/drop_participants_without_ppi_or_ehr.py
> +def get_queries(project_id=None, dataset_id=None, sandbox_dataset_id=None):
Thanks, I missed this. I'll make that change

2021-05-21 15:10 UTC, jp3477 approved these changes
This looks good! Thanks for the changes.

2021-05-21 16:05 UTC, nishanthpp93 commented
There seems to be an unrelated test that's failing. Not sure why.

2021-05-21 21:00 UTC, merged