[DC-1661] Exclude death table from cleaning rule to drop zero concept ids
all-of-us/curation pull request #882
Opened 2021-05-24 22:41 UTC by nishanthpp93

* [DC-1661] Exclude death table

2021-05-25 20:12 UTC, dcampbell-vumc requested changes
Small typo in the doc string comment. The unit test runs as expected however I think we should update the unit test doc string and remove the reference to the death table as well as add the comment you put in the cleaning rule doc string about the change reasoning. That could prevent any future confusion.

2021-05-25 20:12 UTC, dcampbell-vumc commented on data_steward/cdr_cleaner/cleaning_rules/drop_zero_concept_ids.py
> +cause_source_concept_id to persist without being deleted.9
Small typo at end of sentence

```suggestion
cause_source_concept_id to persist without being deleted.
```

2021-05-26 14:20 UTC, nishanthpp93 commented on data_steward/cdr_cleaner/cleaning_rules/drop_zero_concept_ids.py
> +cause_source_concept_id to persist without being deleted.9
Thanks for catching this, I updated it

2021-05-26 15:35 UTC, dcampbell-vumc approved these changes
Thanks for making those changes! Unit test ran successfully so this is good to go!

2021-05-26 18:53 UTC, merged