[DC-1640] Listing Queries In `generate_site_mappings_and_ext_tables` Deletes Extension Tables
all-of-us/curation pull request #887
Opened 2021-05-28 16:57 UTC by dcampbell-vumc

* Converted `generate_ext_tables.py` into cleaning rule
* Removed dependency on `bq_utils.create_tables` to generate extension tables to prevent extension table data loss when listing queries
* Updated `generate_ext_tables_test.py` to reflect changes made in `generate_ext_tables.py` module
* Slight update to how queries are generated in `generate_site_mappings_and_ext_tables.py` module by `generate_ext_tables.py`
* Slight update to mock statement in `generate_site_mappings_and_ext_tables_test.py`
* Moved both `generate_ext_tables.py` and `generate_ext_tables_test.py` to respective cleaning rule folder sections

2021-06-09 19:39 UTC, jp3477 requested changes
Everything here looks good. Should an integration test for `generate_ext_tables.py` be created as well? I also added one minor suggestion.

2021-06-09 19:39 UTC, jp3477 commented on data_steward/tools/add_hpo.py
>      sandbox table created in `generate_site_mappings_and_ext_tables` with any missing hpo_sites in
Can you update the file description to not mention `generate_site_mappings_and_ext_tables`?

2021-06-10 23:29 UTC, lrwb-aou commented
@jp3477 added an integration test and it uncovered a bug.  glad you asked for this.

2021-06-11 18:49 UTC, lrwb-aou commented
@jp3477 finally got the conflicts fixed and the tests passing.

2021-06-11 21:08 UTC, lrwb-aou commented
If @jp3477 approves, please merge it.

2021-06-11 21:57 UTC, jp3477 approved these changes

2021-06-11 21:57 UTC, merged