[DC-1544] Do not start processing a submission until AOU_REQUIRED files are present
all-of-us/curation pull request #967
Opened 2021-09-03 18:26 UTC by jp3477

2021-09-07 13:04 UTC, jp3477 commented
> Am I missing something or this this only ensure the newest file is > 5 minutes old? I don't see any logic to ensure all files are present.

You're correct, thanks for catching that. It should be fixed now.

2021-09-10 19:59 UTC, ksdkalluri commented
@jp3477 Are you still working on this?

2021-09-13 01:29 UTC, jp3477 commented
> @jp3477 Are you still working on this?

No, unless you think it requires more changes.

2021-09-13 14:31 UTC, ksdkalluri requested changes

2021-09-13 14:42 UTC, jp3477 commented on data_steward/validation/main.py
> +            if basename(file_name) in AOU_REQUIRED_FILES:
Yes, you're right, not sure how I missed that. Adding that fix now.

2021-09-13 17:00 UTC, ksdkalluri commented on data_steward/validation/main.py
> +            if basename(file_name) in AOU_REQUIRED_FILES:
@jp3477 my bad the condition should something be like if all files in AOU_REQUIRED_FILES are in files_list then move to next step.

2021-09-14 17:16 UTC, ksdkalluri submitted a review, later dismissed
Good change. I do want to see if the integration tests pass before merging though.

2021-09-24 16:40 UTC, ksdkalluri approved these changes
All the tests that should work are working fine. Thanks for the changes!!

2021-09-24 16:41 UTC, merged